### 使用celery的时候报使用Celery时候报错AttributeError 'float' object has no attribute 'items'

#### 原因

> 这个问题不是因为`celery`的原因, 而是由于`redis`版本的问题. 由于`redis`更新至3.0.0版本后出现此问题. 
>
> `celery`同样因为依赖问题, 导致依赖要求3.0.0之后版本. `GitHub`上的issue[AttributeError: 'float' object has no attribute 'items](https://github.com/celery/celery/issues/5175#)也是讨论了此问题.

#### 解决方案

> 使用如下命令, 对`redis`进行回滚操作:
>
> ```
> pip uninstall redis==2.10.6
> ```

#### 参考

> [使用Celery时候报错AttributeError: 'float' object has no attribute 'items'](<https://blog.csdn.net/weixin_42260750/article/details/84370991>)
>
> [Celery CRITICAL/MainProcess\] Unrecoverable error: AttributeError(“'float' object has no attribute 'items'”,)](https://stackoverflow.com/questions/53322425/celery-critical-mainprocess-unrecoverable-error-attributeerrorfloat-object)
>
> [issue5175](<https://github.com/celery/celery/issues/5175>)

